#include "modules/register_module_types.h"

void initialize_brick_visual_controller_module(ModuleInitializationLevel p_level);
void uninitialize_brick_visual_controller_module(ModuleInitializationLevel p_level);